# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.100.40:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.100.40"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-0"
    ipAddress: "10.0.100.10"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b0:0c:d1:5b:bb:d3"
        dhcp: false
        addresses:
          - "10.0.100.10/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.100.1"
        mtu: 1500
        vip:
          ip: "10.0.100.40"
  - hostname: "talos-1"
    ipAddress: "10.0.100.20"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b0:0c:d1:5a:af:00"
        dhcp: false
        addresses:
          - "10.0.100.20/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.100.1"
        mtu: 1500
        vip:
          ip: "10.0.100.40"
  - hostname: "talos-2"
    ipAddress: "10.0.100.30"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b0:0c:d1:59:b0:ac"
        dhcp: false
        addresses:
          - "10.0.100.30/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.100.1"
        mtu: 1500
        vip:
          ip: "10.0.100.40"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

